name: CI/CD pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Copy files to EC2 via SSH
      uses: appleboy/scp-action@master
      with:
        host: ec2-13-203-205-121.ap-south-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "~/MoonAgentTracker"

    - name: Execute deployment SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ec2-13-203-205-121.ap-south-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/MoonAgentTracker
          docker-compose down
          docker-compose up --build -d
