name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-203-205-121.ap-south-1.compute.amazonaws.com << 'EOF'
            cd ~/Moon-Agent-Tracker/MoonAgentTracker
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF
